---
- hosts: tacoserver
  sudo: yes
  roles:
    - nodejs
  tasks:
    - name: Iniciar la aplicacion
      command: forever start /var/app/tacos.js
    - name: Env
      debug: msg="Env {{ env_name }}"

